// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "proto/product.proto" (package "pb", syntax proto3)
// tslint:disable

import * as grpc from "@grpc/grpc-js";
import type {
	BinaryReadOptions,
	BinaryWriteOptions,
} from "@protobuf-ts/runtime";
import type {
	CreateProductRequest,
	DeleteProductRequest,
	Empty,
	GetProductRequest,
	ListProductsRequest,
	ListProductsResponse,
	Product,
	UpdateProductRequest,
} from "./product";
import { ProductService } from "./product";
/**
 * @generated from protobuf service pb.ProductService
 */
export interface IProductServiceClient {
	/**
	 * @generated from protobuf rpc: Create
	 */
	create(
		input: CreateProductRequest,
		metadata: grpc.Metadata,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	create(
		input: CreateProductRequest,
		metadata: grpc.Metadata,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	create(
		input: CreateProductRequest,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	create(
		input: CreateProductRequest,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	/**
	 * @generated from protobuf rpc: Get
	 */
	get(
		input: GetProductRequest,
		metadata: grpc.Metadata,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	get(
		input: GetProductRequest,
		metadata: grpc.Metadata,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	get(
		input: GetProductRequest,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	get(
		input: GetProductRequest,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	/**
	 * @generated from protobuf rpc: Update
	 */
	update(
		input: UpdateProductRequest,
		metadata: grpc.Metadata,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	update(
		input: UpdateProductRequest,
		metadata: grpc.Metadata,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	update(
		input: UpdateProductRequest,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	update(
		input: UpdateProductRequest,
		callback: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall;
	/**
	 * @generated from protobuf rpc: Delete
	 */
	delete(
		input: DeleteProductRequest,
		metadata: grpc.Metadata,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Empty) => void,
	): grpc.ClientUnaryCall;
	delete(
		input: DeleteProductRequest,
		metadata: grpc.Metadata,
		callback: (err: grpc.ServiceError | null, value?: Empty) => void,
	): grpc.ClientUnaryCall;
	delete(
		input: DeleteProductRequest,
		options: grpc.CallOptions,
		callback: (err: grpc.ServiceError | null, value?: Empty) => void,
	): grpc.ClientUnaryCall;
	delete(
		input: DeleteProductRequest,
		callback: (err: grpc.ServiceError | null, value?: Empty) => void,
	): grpc.ClientUnaryCall;
	/**
	 * @generated from protobuf rpc: List
	 */
	list(
		input: ListProductsRequest,
		metadata: grpc.Metadata,
		options: grpc.CallOptions,
		callback: (
			err: grpc.ServiceError | null,
			value?: ListProductsResponse,
		) => void,
	): grpc.ClientUnaryCall;
	list(
		input: ListProductsRequest,
		metadata: grpc.Metadata,
		callback: (
			err: grpc.ServiceError | null,
			value?: ListProductsResponse,
		) => void,
	): grpc.ClientUnaryCall;
	list(
		input: ListProductsRequest,
		options: grpc.CallOptions,
		callback: (
			err: grpc.ServiceError | null,
			value?: ListProductsResponse,
		) => void,
	): grpc.ClientUnaryCall;
	list(
		input: ListProductsRequest,
		callback: (
			err: grpc.ServiceError | null,
			value?: ListProductsResponse,
		) => void,
	): grpc.ClientUnaryCall;
}
/**
 * @generated from protobuf service pb.ProductService
 */
export class ProductServiceClient
	extends grpc.Client
	implements IProductServiceClient
{
	private readonly _binaryOptions: Partial<
		BinaryReadOptions & BinaryWriteOptions
	>;
	constructor(
		address: string,
		credentials: grpc.ChannelCredentials,
		options: grpc.ClientOptions = {},
		binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {},
	) {
		super(address, credentials, options);
		this._binaryOptions = binaryOptions;
	}
	/**
	 * @generated from protobuf rpc: Create
	 */
	create(
		input: CreateProductRequest,
		metadata:
			| grpc.Metadata
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		options?:
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		callback?: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall {
		const method = ProductService.methods[0];
		return this.makeUnaryRequest<CreateProductRequest, Product>(
			`/${ProductService.typeName}/${method.name}`,
			(value: CreateProductRequest): Buffer =>
				Buffer.from(method.I.toBinary(value, this._binaryOptions)),
			(value: Buffer): Product =>
				method.O.fromBinary(value, this._binaryOptions),
			input,
			metadata as any,
			options as any,
			callback as any,
		);
	}
	/**
	 * @generated from protobuf rpc: Get
	 */
	get(
		input: GetProductRequest,
		metadata:
			| grpc.Metadata
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		options?:
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		callback?: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall {
		const method = ProductService.methods[1];
		return this.makeUnaryRequest<GetProductRequest, Product>(
			`/${ProductService.typeName}/${method.name}`,
			(value: GetProductRequest): Buffer =>
				Buffer.from(method.I.toBinary(value, this._binaryOptions)),
			(value: Buffer): Product =>
				method.O.fromBinary(value, this._binaryOptions),
			input,
			metadata as any,
			options as any,
			callback as any,
		);
	}
	/**
	 * @generated from protobuf rpc: Update
	 */
	update(
		input: UpdateProductRequest,
		metadata:
			| grpc.Metadata
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		options?:
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Product) => void),
		callback?: (err: grpc.ServiceError | null, value?: Product) => void,
	): grpc.ClientUnaryCall {
		const method = ProductService.methods[2];
		return this.makeUnaryRequest<UpdateProductRequest, Product>(
			`/${ProductService.typeName}/${method.name}`,
			(value: UpdateProductRequest): Buffer =>
				Buffer.from(method.I.toBinary(value, this._binaryOptions)),
			(value: Buffer): Product =>
				method.O.fromBinary(value, this._binaryOptions),
			input,
			metadata as any,
			options as any,
			callback as any,
		);
	}
	/**
	 * @generated from protobuf rpc: Delete
	 */
	delete(
		input: DeleteProductRequest,
		metadata:
			| grpc.Metadata
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Empty) => void),
		options?:
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: Empty) => void),
		callback?: (err: grpc.ServiceError | null, value?: Empty) => void,
	): grpc.ClientUnaryCall {
		const method = ProductService.methods[3];
		return this.makeUnaryRequest<DeleteProductRequest, Empty>(
			`/${ProductService.typeName}/${method.name}`,
			(value: DeleteProductRequest): Buffer =>
				Buffer.from(method.I.toBinary(value, this._binaryOptions)),
			(value: Buffer): Empty => method.O.fromBinary(value, this._binaryOptions),
			input,
			metadata as any,
			options as any,
			callback as any,
		);
	}
	/**
	 * @generated from protobuf rpc: List
	 */
	list(
		input: ListProductsRequest,
		metadata:
			| grpc.Metadata
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: ListProductsResponse) => void),
		options?:
			| grpc.CallOptions
			| ((err: grpc.ServiceError | null, value?: ListProductsResponse) => void),
		callback?: (
			err: grpc.ServiceError | null,
			value?: ListProductsResponse,
		) => void,
	): grpc.ClientUnaryCall {
		const method = ProductService.methods[4];
		return this.makeUnaryRequest<ListProductsRequest, ListProductsResponse>(
			`/${ProductService.typeName}/${method.name}`,
			(value: ListProductsRequest): Buffer =>
				Buffer.from(method.I.toBinary(value, this._binaryOptions)),
			(value: Buffer): ListProductsResponse =>
				method.O.fromBinary(value, this._binaryOptions),
			input,
			metadata as any,
			options as any,
			callback as any,
		);
	}
}
