// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "proto/product.proto" (package "pb", syntax proto3)
// tslint:disable

import type {
	BinaryReadOptions,
	BinaryWriteOptions,
	IBinaryReader,
	IBinaryWriter,
	PartialMessage,
} from "@protobuf-ts/runtime";
import {
	MessageType,
	reflectionMergePartial,
	UnknownFieldHandler,
	WireType,
} from "@protobuf-ts/runtime";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf message pb.Product
 */
export interface Product {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
	/**
	 * @generated from protobuf field: string name = 2
	 */
	name: string;
	/**
	 * @generated from protobuf field: double price = 3
	 */
	price: number;
	/**
	 * @generated from protobuf field: int32 quantity = 4
	 */
	quantity: number;
}
/**
 * @generated from protobuf message pb.CreateProductRequest
 */
export interface CreateProductRequest {
	/**
	 * @generated from protobuf field: string name = 1
	 */
	name: string;
	/**
	 * @generated from protobuf field: double price = 2
	 */
	price: number;
	/**
	 * @generated from protobuf field: int32 quantity = 3
	 */
	quantity: number;
}
/**
 * @generated from protobuf message pb.GetProductRequest
 */
export interface GetProductRequest {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
}
/**
 * @generated from protobuf message pb.UpdateProductRequest
 */
export interface UpdateProductRequest {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
	/**
	 * @generated from protobuf field: string name = 2
	 */
	name: string;
	/**
	 * @generated from protobuf field: double price = 3
	 */
	price: number;
	/**
	 * @generated from protobuf field: int32 quantity = 4
	 */
	quantity: number;
}
/**
 * @generated from protobuf message pb.DeleteProductRequest
 */
export interface DeleteProductRequest {
	/**
	 * @generated from protobuf field: string id = 1
	 */
	id: string;
}
/**
 * @generated from protobuf message pb.ListProductsRequest
 */
export type ListProductsRequest = {};
/**
 * @generated from protobuf message pb.ListProductsResponse
 */
export interface ListProductsResponse {
	/**
	 * @generated from protobuf field: repeated pb.Product products = 1
	 */
	products: Product[];
}
/**
 * @generated from protobuf message pb.Empty
 */
export type Empty = {};
// @generated message type with reflection information, may provide speed optimized methods
class Product$Type extends MessageType<Product> {
	constructor() {
		super("pb.Product", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
			{ no: 4, name: "quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
		]);
	}
	create(value?: PartialMessage<Product>): Product {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		message.name = "";
		message.price = 0;
		message.quantity = 0;
		if (value !== undefined)
			reflectionMergePartial<Product>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: Product,
	): Product {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				case /* string name */ 2:
					message.name = reader.string();
					break;
				case /* double price */ 3:
					message.price = reader.double();
					break;
				case /* int32 quantity */ 4:
					message.quantity = reader.int32();
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: Product,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.id);
		/* string name = 2; */
		if (message.name !== "")
			writer.tag(2, WireType.LengthDelimited).string(message.name);
		/* double price = 3; */
		if (message.price !== 0)
			writer.tag(3, WireType.Bit64).double(message.price);
		/* int32 quantity = 4; */
		if (message.quantity !== 0)
			writer.tag(4, WireType.Varint).int32(message.quantity);
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.Product
 */
export const Product = new Product$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateProductRequest$Type extends MessageType<CreateProductRequest> {
	constructor() {
		super("pb.CreateProductRequest", [
			{ no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
			{ no: 3, name: "quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
		]);
	}
	create(value?: PartialMessage<CreateProductRequest>): CreateProductRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.name = "";
		message.price = 0;
		message.quantity = 0;
		if (value !== undefined)
			reflectionMergePartial<CreateProductRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: CreateProductRequest,
	): CreateProductRequest {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string name */ 1:
					message.name = reader.string();
					break;
				case /* double price */ 2:
					message.price = reader.double();
					break;
				case /* int32 quantity */ 3:
					message.quantity = reader.int32();
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: CreateProductRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string name = 1; */
		if (message.name !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.name);
		/* double price = 2; */
		if (message.price !== 0)
			writer.tag(2, WireType.Bit64).double(message.price);
		/* int32 quantity = 3; */
		if (message.quantity !== 0)
			writer.tag(3, WireType.Varint).int32(message.quantity);
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.CreateProductRequest
 */
export const CreateProductRequest = new CreateProductRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProductRequest$Type extends MessageType<GetProductRequest> {
	constructor() {
		super("pb.GetProductRequest", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<GetProductRequest>): GetProductRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		if (value !== undefined)
			reflectionMergePartial<GetProductRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: GetProductRequest,
	): GetProductRequest {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: GetProductRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.id);
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.GetProductRequest
 */
export const GetProductRequest = new GetProductRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateProductRequest$Type extends MessageType<UpdateProductRequest> {
	constructor() {
		super("pb.UpdateProductRequest", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: "price", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
			{ no: 4, name: "quantity", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
		]);
	}
	create(value?: PartialMessage<UpdateProductRequest>): UpdateProductRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		message.name = "";
		message.price = 0;
		message.quantity = 0;
		if (value !== undefined)
			reflectionMergePartial<UpdateProductRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: UpdateProductRequest,
	): UpdateProductRequest {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				case /* string name */ 2:
					message.name = reader.string();
					break;
				case /* double price */ 3:
					message.price = reader.double();
					break;
				case /* int32 quantity */ 4:
					message.quantity = reader.int32();
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: UpdateProductRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.id);
		/* string name = 2; */
		if (message.name !== "")
			writer.tag(2, WireType.LengthDelimited).string(message.name);
		/* double price = 3; */
		if (message.price !== 0)
			writer.tag(3, WireType.Bit64).double(message.price);
		/* int32 quantity = 4; */
		if (message.quantity !== 0)
			writer.tag(4, WireType.Varint).int32(message.quantity);
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.UpdateProductRequest
 */
export const UpdateProductRequest = new UpdateProductRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteProductRequest$Type extends MessageType<DeleteProductRequest> {
	constructor() {
		super("pb.DeleteProductRequest", [
			{ no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<DeleteProductRequest>): DeleteProductRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = "";
		if (value !== undefined)
			reflectionMergePartial<DeleteProductRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: DeleteProductRequest,
	): DeleteProductRequest {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* string id */ 1:
					message.id = reader.string();
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: DeleteProductRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* string id = 1; */
		if (message.id !== "")
			writer.tag(1, WireType.LengthDelimited).string(message.id);
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.DeleteProductRequest
 */
export const DeleteProductRequest = new DeleteProductRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListProductsRequest$Type extends MessageType<ListProductsRequest> {
	constructor() {
		super("pb.ListProductsRequest", []);
	}
	create(value?: PartialMessage<ListProductsRequest>): ListProductsRequest {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined)
			reflectionMergePartial<ListProductsRequest>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: ListProductsRequest,
	): ListProductsRequest {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: ListProductsRequest,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.ListProductsRequest
 */
export const ListProductsRequest = new ListProductsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListProductsResponse$Type extends MessageType<ListProductsResponse> {
	constructor() {
		super("pb.ListProductsResponse", [
			{
				no: 1,
				name: "products",
				kind: "message",
				repeat: 2 /*RepeatType.UNPACKED*/,
				T: () => Product,
			},
		]);
	}
	create(value?: PartialMessage<ListProductsResponse>): ListProductsResponse {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.products = [];
		if (value !== undefined)
			reflectionMergePartial<ListProductsResponse>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: ListProductsResponse,
	): ListProductsResponse {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* repeated pb.Product products */ 1:
					message.products.push(
						Product.internalBinaryRead(reader, reader.uint32(), options),
					);
					break;
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: ListProductsResponse,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		/* repeated pb.Product products = 1; */
		for (let i = 0; i < message.products.length; i++)
			Product.internalBinaryWrite(
				message.products[i],
				writer.tag(1, WireType.LengthDelimited).fork(),
				options,
			).join();
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.ListProductsResponse
 */
export const ListProductsResponse = new ListProductsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Empty$Type extends MessageType<Empty> {
	constructor() {
		super("pb.Empty", []);
	}
	create(value?: PartialMessage<Empty>): Empty {
		const message = globalThis.Object.create(this.messagePrototype!);
		if (value !== undefined)
			reflectionMergePartial<Empty>(this, message, value);
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: Empty,
	): Empty {
		const message = target ?? this.create(),
			end = reader.pos + length;
		while (reader.pos < end) {
			const [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				default: {
					const u = options.readUnknownField;
					if (u === "throw")
						throw new globalThis.Error(
							`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
						);
					const d = reader.skip(wireType);
					if (u !== false)
						(u === true ? UnknownFieldHandler.onRead : u)(
							this.typeName,
							message,
							fieldNo,
							wireType,
							d,
						);
				}
			}
		}
		return message;
	}
	internalBinaryWrite(
		message: Empty,
		writer: IBinaryWriter,
		options: BinaryWriteOptions,
	): IBinaryWriter {
		const u = options.writeUnknownFields;
		if (u !== false)
			(u == true ? UnknownFieldHandler.onWrite : u)(
				this.typeName,
				message,
				writer,
			);
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message pb.Empty
 */
export const Empty = new Empty$Type();
/**
 * @generated ServiceType for protobuf service pb.ProductService
 */
export const ProductService = new ServiceType("pb.ProductService", [
	{ name: "Create", options: {}, I: CreateProductRequest, O: Product },
	{ name: "Get", options: {}, I: GetProductRequest, O: Product },
	{ name: "Update", options: {}, I: UpdateProductRequest, O: Product },
	{ name: "Delete", options: {}, I: DeleteProductRequest, O: Empty },
	{
		name: "List",
		options: {},
		I: ListProductsRequest,
		O: ListProductsResponse,
	},
]);
